config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "top_page#index"

  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[index edit show new create update] do
    resources :identifications, only: %i[show edit]
    resources :children, only: %i[index edit show new create update]
    resources :group_members, only: %i[index]
    resources :block_members, only: %i[index]
    resources :messages, only: %i[index show]
  end

  resources :playgrounds, only: %i[index edit show new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :playgrounds, dependent: :nullify
  has_many :user, dependent: :nullify
end

app/models/block_member.rb
class BlockMember < ApplicationRecord
  belongs_to :user, class_name: 'User', :foreign_key => 'user_id'
  belongs_to :target_user, class_name: 'User', :foreign_key => 'target_user_id'
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :user
  belongs_to :favorite_character

  enum gender_types: {
      female: 0,
      male: 1,
      unanswered: 2
  }
end

app/models/favorite_character.rb
class FavoriteCharacter < ApplicationRecord
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :user, class_name: 'User', :foreign_key => 'user_id'
  belongs_to :target_user, class_name: 'User', :foreign_key => 'target_user_id'

end

app/models/identification.rb
class Identification < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, class_name: 'User', :foreign_key => 'user_id'
  belongs_to :target_user, class_name: 'User', :foreign_key => 'target_user_id'
end

app/models/playground.rb
class Playground < ApplicationRecord
  belongs_to :area, optional: true
  belongs_to :playng_type
end

app/models/playing_type.rb
class PlayingType < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  belongs_to :area
  has_one :Identification
  has_many :children, dependent: :destroy
  has_many :group_members_user, class_name: 'GroupMember', :foreign_key => 'user_id', dependent: :destroy
  has_many :group_members_target, class_name: 'GroupMember', :foreign_key => 'target_user_id', dependent: :destroy
  has_many :block_members_user, class_name: 'BlockMember', :foreign_key => 'user_id', dependent: :destroy
  has_many :block_members_target, class_name: 'BlockMember', :foreign_key => 'target_user_id', dependent: :destroy
  has_many :messages_user, class_name: 'Message', :foreign_key => 'user_id', dependent: :destroy
  has_many :messages_target, class_name: 'Message', :foreign_key => 'target_user_id', dependent: :destroy
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @children = @user.children.all
  end

  def show
    @user = User.find(params[:user_id])
    @child = @user.children.find(params[:id])
  end

  def edit
    @user = current_user
    @child = @user.children.find
  end

  def new
    @user = current_user
    @child = @user.children.new
  end

  def create
    child = current_user.children.build(set_params)
    
    if child.save
      flash[:success] = 'こども情報登録完了'
      redirect_to user_path(current_user)
    else
      flash[:danger] = 'こども情報登録失敗'
      redirect_to new_user_child_path(current_user)
    end
  end
  
  def update
    child = current_user.children.find(params[:id])
    if child.update(set_params)
      redirect_to child_path(user,child), success: 'こども情報更新完了'
    else
      flash[:danger] = 'こども情報更新に失敗しました。'
      render :edit
    end

  end

  def set_params
    params.require(:child).permit(:avatar_name, :gender, :age, :profile, :character, :favorite_character_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index; end

  def show; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @area = @user.area_id == nil ? '未設定' : Area.find(@user.area_id).address
  end

  def edit
    @user = current_user
    @areas = Area.all.map { |area| [area.address, area.id] }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(set_params)
    
    if @user.save
      flash[:success] = '登録成功'
      redirect_to user_path(@user)
    else
      flash[:danger] = '登録失敗'
      redirect_back_or_to new_user_path
    end
  end
  
  def update
    user = current_user
    if user.update(set_params)
      flash[:success] = 'ユーザー情報更新完了'
      redirect_to user_path(user)
    else
      flash['danger'] = 'ユーザー情報更新に失敗しました。'
      redirect_to new_user_path
    end

  end

  def set_params
    params.require(:user).permit(:avatar_name, :email, :password, :password_confirmation, :profile, :area_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/block_members_helper.rb
module BlockMembersHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/identifications_helper.rb
module IdentificationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users/children_helper.rb
module Users::ChildrenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
users#{user_id}#edit

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>

<div>
  <%= form_with model: @user, local: true do |form| %>
    <div>
      <%= form.label :avatar_name %>
      <%= form.text_field :avatar_name %>
    </div>
    <div>
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div>
      <%= form.label :area_id %>
      <%= form.select :area_id, Area.all.map { |area| [area.address, area.id] } %>
    </div>
    <div>
      <%= form.label :profile %>
      <%= form.text_field :profile %>
    </div>
    <%= form.submit '登録' %>
  <% end %>
</div>

app/views/users/index.erb
users#index

app/views/users/index.html.erb
users#index
<h1>ユーザー検索</h1>

<div>
  <% @users.each do |user| %>
    <div>
      <%= link_to user.avatar_name, user_path(user) %>
    </div>
  <% end %>
<div>

app/views/users/new.html.erb
<div>
  <h1>ユーザー登録</h1>
  <%= form_with model: @user, local: true do |form| %>
    <div>
      <%= form.label :avatar_name %>
      <%= form.text_field :avatar_name %>
    </div>
    <div>
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div>
    <div>
      <%= form.label :area_id %>
      <%= form.collection_select :area_id, Area.all, :id, :address %>
    </div>
    <div>
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
    <%= form.submit '登録' %>
  <% end %>
</div>

app/views/users/show.erb
users#show

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
<div>ユーザー名：
  <%= @user.avatar_name %>
</div>
<div>地域:
  <%= @area %>
</div>
<div>プロフィール：
  <%= @user.profile %>
</div>
<div>



<div>
  <%= link_to 'ユーザー検索', users_path %>
</div>
<div>
  <%= link_to '子供情報一覧', user_children_path(@user) %>
</div>

<% if @user == current_user %>
<div>
  <%= link_to '子供情報登録', new_user_child_path(@user) %>
</div>
<div>
  <%= link_to 'ユーザー情報編集', edit_user_path %>
</div>
<% end %>